// Code generated by go-swagger; DO NOT EDIT.

package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewNeutronInterchainadapterInterchainqueriesParamsParams creates a new NeutronInterchainadapterInterchainqueriesParamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewNeutronInterchainadapterInterchainqueriesParamsParams() *NeutronInterchainadapterInterchainqueriesParamsParams {
	return &NeutronInterchainadapterInterchainqueriesParamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewNeutronInterchainadapterInterchainqueriesParamsParamsWithTimeout creates a new NeutronInterchainadapterInterchainqueriesParamsParams object
// with the ability to set a timeout on a request.
func NewNeutronInterchainadapterInterchainqueriesParamsParamsWithTimeout(timeout time.Duration) *NeutronInterchainadapterInterchainqueriesParamsParams {
	return &NeutronInterchainadapterInterchainqueriesParamsParams{
		timeout: timeout,
	}
}

// NewNeutronInterchainadapterInterchainqueriesParamsParamsWithContext creates a new NeutronInterchainadapterInterchainqueriesParamsParams object
// with the ability to set a context for a request.
func NewNeutronInterchainadapterInterchainqueriesParamsParamsWithContext(ctx context.Context) *NeutronInterchainadapterInterchainqueriesParamsParams {
	return &NeutronInterchainadapterInterchainqueriesParamsParams{
		Context: ctx,
	}
}

// NewNeutronInterchainadapterInterchainqueriesParamsParamsWithHTTPClient creates a new NeutronInterchainadapterInterchainqueriesParamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewNeutronInterchainadapterInterchainqueriesParamsParamsWithHTTPClient(client *http.Client) *NeutronInterchainadapterInterchainqueriesParamsParams {
	return &NeutronInterchainadapterInterchainqueriesParamsParams{
		HTTPClient: client,
	}
}

/* NeutronInterchainadapterInterchainqueriesParamsParams contains all the parameters to send to the API endpoint
   for the neutron interchainadapter interchainqueries params operation.

   Typically these are written to a http.Request.
*/
type NeutronInterchainadapterInterchainqueriesParamsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the neutron interchainadapter interchainqueries params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NeutronInterchainadapterInterchainqueriesParamsParams) WithDefaults() *NeutronInterchainadapterInterchainqueriesParamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the neutron interchainadapter interchainqueries params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NeutronInterchainadapterInterchainqueriesParamsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the neutron interchainadapter interchainqueries params params
func (o *NeutronInterchainadapterInterchainqueriesParamsParams) WithTimeout(timeout time.Duration) *NeutronInterchainadapterInterchainqueriesParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the neutron interchainadapter interchainqueries params params
func (o *NeutronInterchainadapterInterchainqueriesParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the neutron interchainadapter interchainqueries params params
func (o *NeutronInterchainadapterInterchainqueriesParamsParams) WithContext(ctx context.Context) *NeutronInterchainadapterInterchainqueriesParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the neutron interchainadapter interchainqueries params params
func (o *NeutronInterchainadapterInterchainqueriesParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the neutron interchainadapter interchainqueries params params
func (o *NeutronInterchainadapterInterchainqueriesParamsParams) WithHTTPClient(client *http.Client) *NeutronInterchainadapterInterchainqueriesParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the neutron interchainadapter interchainqueries params params
func (o *NeutronInterchainadapterInterchainqueriesParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *NeutronInterchainadapterInterchainqueriesParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
