// Code generated by go-swagger; DO NOT EDIT.

package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NeutronInterchainadapterInterchainqueriesParamsReader is a Reader for the NeutronInterchainadapterInterchainqueriesParams structure.
type NeutronInterchainadapterInterchainqueriesParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NeutronInterchainadapterInterchainqueriesParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNeutronInterchainadapterInterchainqueriesParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewNeutronInterchainadapterInterchainqueriesParamsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewNeutronInterchainadapterInterchainqueriesParamsOK creates a NeutronInterchainadapterInterchainqueriesParamsOK with default headers values
func NewNeutronInterchainadapterInterchainqueriesParamsOK() *NeutronInterchainadapterInterchainqueriesParamsOK {
	return &NeutronInterchainadapterInterchainqueriesParamsOK{}
}

/* NeutronInterchainadapterInterchainqueriesParamsOK describes a response with status code 200, with default header values.

A successful response.
*/
type NeutronInterchainadapterInterchainqueriesParamsOK struct {
	Payload *NeutronInterchainadapterInterchainqueriesParamsOKBody
}

func (o *NeutronInterchainadapterInterchainqueriesParamsOK) Error() string {
	return fmt.Sprintf("[GET /neutron/interchainqueries/interchainqueries/params][%d] neutronInterchainadapterInterchainqueriesParamsOK  %+v", 200, o.Payload)
}
func (o *NeutronInterchainadapterInterchainqueriesParamsOK) GetPayload() *NeutronInterchainadapterInterchainqueriesParamsOKBody {
	return o.Payload
}

func (o *NeutronInterchainadapterInterchainqueriesParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(NeutronInterchainadapterInterchainqueriesParamsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNeutronInterchainadapterInterchainqueriesParamsDefault creates a NeutronInterchainadapterInterchainqueriesParamsDefault with default headers values
func NewNeutronInterchainadapterInterchainqueriesParamsDefault(code int) *NeutronInterchainadapterInterchainqueriesParamsDefault {
	return &NeutronInterchainadapterInterchainqueriesParamsDefault{
		_statusCode: code,
	}
}

/* NeutronInterchainadapterInterchainqueriesParamsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type NeutronInterchainadapterInterchainqueriesParamsDefault struct {
	_statusCode int

	Payload *NeutronInterchainadapterInterchainqueriesParamsDefaultBody
}

// Code gets the status code for the neutron interchainadapter interchainqueries params default response
func (o *NeutronInterchainadapterInterchainqueriesParamsDefault) Code() int {
	return o._statusCode
}

func (o *NeutronInterchainadapterInterchainqueriesParamsDefault) Error() string {
	return fmt.Sprintf("[GET /neutron/interchainqueries/interchainqueries/params][%d] NeutronInterchainadapterInterchainqueriesParams default  %+v", o._statusCode, o.Payload)
}
func (o *NeutronInterchainadapterInterchainqueriesParamsDefault) GetPayload() *NeutronInterchainadapterInterchainqueriesParamsDefaultBody {
	return o.Payload
}

func (o *NeutronInterchainadapterInterchainqueriesParamsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(NeutronInterchainadapterInterchainqueriesParamsDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*NeutronInterchainadapterInterchainqueriesParamsDefaultBody neutron interchainadapter interchainqueries params default body
swagger:model NeutronInterchainadapterInterchainqueriesParamsDefaultBody
*/
type NeutronInterchainadapterInterchainqueriesParamsDefaultBody struct {

	// code
	Code int32 `json:"code,omitempty"`

	// details
	Details []*NeutronInterchainadapterInterchainqueriesParamsDefaultBodyDetailsItems0 `json:"details"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this neutron interchainadapter interchainqueries params default body
func (o *NeutronInterchainadapterInterchainqueriesParamsDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *NeutronInterchainadapterInterchainqueriesParamsDefaultBody) validateDetails(formats strfmt.Registry) error {
	if swag.IsZero(o.Details) { // not required
		return nil
	}

	for i := 0; i < len(o.Details); i++ {
		if swag.IsZero(o.Details[i]) { // not required
			continue
		}

		if o.Details[i] != nil {
			if err := o.Details[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("NeutronInterchainadapterInterchainqueriesParams default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this neutron interchainadapter interchainqueries params default body based on the context it is used
func (o *NeutronInterchainadapterInterchainqueriesParamsDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *NeutronInterchainadapterInterchainqueriesParamsDefaultBody) contextValidateDetails(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Details); i++ {

		if o.Details[i] != nil {
			if err := o.Details[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("NeutronInterchainadapterInterchainqueriesParams default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *NeutronInterchainadapterInterchainqueriesParamsDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *NeutronInterchainadapterInterchainqueriesParamsDefaultBody) UnmarshalBinary(b []byte) error {
	var res NeutronInterchainadapterInterchainqueriesParamsDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*NeutronInterchainadapterInterchainqueriesParamsDefaultBodyDetailsItems0 `Any` contains an arbitrary serialized protocol buffer message along with a
// URL that describes the type of the serialized message.
//
// Protobuf library provides support to pack/unpack Any values in the form
// of utility functions or additional generated methods of the Any type.
//
// Example 1: Pack and unpack a message in C++.
//
//     Foo foo = ...;
//     Any any;
//     any.PackFrom(foo);
//     ...
//     if (any.UnpackTo(&foo)) {
//       ...
//     }
//
// Example 2: Pack and unpack a message in Java.
//
//     Foo foo = ...;
//     Any any = Any.pack(foo);
//     ...
//     if (any.is(Foo.class)) {
//       foo = any.unpack(Foo.class);
//     }
//
//  Example 3: Pack and unpack a message in Python.
//
//     foo = Foo(...)
//     any = Any()
//     any.Pack(foo)
//     ...
//     if any.Is(Foo.DESCRIPTOR):
//       any.Unpack(foo)
//       ...
//
//  Example 4: Pack and unpack a message in Go
//
//      foo := &pb.Foo{...}
//      any, err := anypb.New(foo)
//      if err != nil {
//        ...
//      }
//      ...
//      foo := &pb.Foo{}
//      if err := any.UnmarshalTo(foo); err != nil {
//        ...
//      }
//
// The pack methods provided by protobuf library will by default use
// 'type.googleapis.com/full.type.name' as the type URL and the unpack
// methods only use the fully qualified type name after the last '/'
// in the type URL, for example "foo.bar.com/x/y.z" will yield type
// name "y.z".
//
//
// JSON
// ====
// The JSON representation of an `Any` value uses the regular
// representation of the deserialized, embedded message, with an
// additional field `@type` which contains the type URL. Example:
//
//     package google.profile;
//     message Person {
//       string first_name = 1;
//       string last_name = 2;
//     }
//
//     {
//       "@type": "type.googleapis.com/google.profile.Person",
//       "firstName": <string>,
//       "lastName": <string>
//     }
//
// If the embedded message type is well-known and has a custom JSON
// representation, that representation will be embedded adding a field
// `value` which holds the custom JSON in addition to the `@type`
// field. Example (for message [google.protobuf.Duration][]):
//
//     {
//       "@type": "type.googleapis.com/google.protobuf.Duration",
//       "value": "1.212s"
//     }
swagger:model NeutronInterchainadapterInterchainqueriesParamsDefaultBodyDetailsItems0
*/
type NeutronInterchainadapterInterchainqueriesParamsDefaultBodyDetailsItems0 struct {

	// A URL/resource name that uniquely identifies the type of the serialized
	// protocol buffer message. This string must contain at least
	// one "/" character. The last segment of the URL's path must represent
	// the fully qualified name of the type (as in
	// `path/google.protobuf.Duration`). The name should be in a canonical form
	// (e.g., leading "." is not accepted).
	//
	// In practice, teams usually precompile into the binary all types that they
	// expect it to use in the context of Any. However, for URLs which use the
	// scheme `http`, `https`, or no scheme, one can optionally set up a type
	// server that maps type URLs to message definitions as follows:
	//
	// * If no scheme is provided, `https` is assumed.
	// * An HTTP GET on the URL must yield a [google.protobuf.Type][]
	//   value in binary format, or produce an error.
	// * Applications are allowed to cache lookup results based on the
	//   URL, or have them precompiled into a binary to avoid any
	//   lookup. Therefore, binary compatibility needs to be preserved
	//   on changes to types. (Use versioned type names to manage
	//   breaking changes.)
	//
	// Note: this functionality is not currently available in the official
	// protobuf release, and it is not used for type URLs beginning with
	// type.googleapis.com.
	//
	// Schemes other than `http`, `https` (or the empty scheme) might be
	// used with implementation specific semantics.
	AtType string `json:"@type,omitempty"`
}

// Validate validates this neutron interchainadapter interchainqueries params default body details items0
func (o *NeutronInterchainadapterInterchainqueriesParamsDefaultBodyDetailsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this neutron interchainadapter interchainqueries params default body details items0 based on context it is used
func (o *NeutronInterchainadapterInterchainqueriesParamsDefaultBodyDetailsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *NeutronInterchainadapterInterchainqueriesParamsDefaultBodyDetailsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *NeutronInterchainadapterInterchainqueriesParamsDefaultBodyDetailsItems0) UnmarshalBinary(b []byte) error {
	var res NeutronInterchainadapterInterchainqueriesParamsDefaultBodyDetailsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*NeutronInterchainadapterInterchainqueriesParamsOKBody QueryParamsResponse is response type for the Query/Params RPC method.
swagger:model NeutronInterchainadapterInterchainqueriesParamsOKBody
*/
type NeutronInterchainadapterInterchainqueriesParamsOKBody struct {

	// params holds all the parameters of this module.
	Params interface{} `json:"params,omitempty"`
}

// Validate validates this neutron interchainadapter interchainqueries params o k body
func (o *NeutronInterchainadapterInterchainqueriesParamsOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this neutron interchainadapter interchainqueries params o k body based on context it is used
func (o *NeutronInterchainadapterInterchainqueriesParamsOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *NeutronInterchainadapterInterchainqueriesParamsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *NeutronInterchainadapterInterchainqueriesParamsOKBody) UnmarshalBinary(b []byte) error {
	var res NeutronInterchainadapterInterchainqueriesParamsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
