// Code generated by go-swagger; DO NOT EDIT.

package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewNeutronInterchainQueriesRegisteredQueriesParams creates a new NeutronInterchainQueriesRegisteredQueriesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewNeutronInterchainQueriesRegisteredQueriesParams() *NeutronInterchainQueriesRegisteredQueriesParams {
	return &NeutronInterchainQueriesRegisteredQueriesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewNeutronInterchainQueriesRegisteredQueriesParamsWithTimeout creates a new NeutronInterchainQueriesRegisteredQueriesParams object
// with the ability to set a timeout on a request.
func NewNeutronInterchainQueriesRegisteredQueriesParamsWithTimeout(timeout time.Duration) *NeutronInterchainQueriesRegisteredQueriesParams {
	return &NeutronInterchainQueriesRegisteredQueriesParams{
		timeout: timeout,
	}
}

// NewNeutronInterchainQueriesRegisteredQueriesParamsWithContext creates a new NeutronInterchainQueriesRegisteredQueriesParams object
// with the ability to set a context for a request.
func NewNeutronInterchainQueriesRegisteredQueriesParamsWithContext(ctx context.Context) *NeutronInterchainQueriesRegisteredQueriesParams {
	return &NeutronInterchainQueriesRegisteredQueriesParams{
		Context: ctx,
	}
}

// NewNeutronInterchainQueriesRegisteredQueriesParamsWithHTTPClient creates a new NeutronInterchainQueriesRegisteredQueriesParams object
// with the ability to set a custom HTTPClient for a request.
func NewNeutronInterchainQueriesRegisteredQueriesParamsWithHTTPClient(client *http.Client) *NeutronInterchainQueriesRegisteredQueriesParams {
	return &NeutronInterchainQueriesRegisteredQueriesParams{
		HTTPClient: client,
	}
}

/*
NeutronInterchainQueriesRegisteredQueriesParams contains all the parameters to send to the API endpoint

	for the neutron interchain queries registered queries operation.

	Typically these are written to a http.Request.
*/
type NeutronInterchainQueriesRegisteredQueriesParams struct {

	// ConnectionID.
	ConnectionID *string

	// Owners.
	Owners []string

	/* PaginationCountTotal.

	     count_total is set to true  to indicate that the result set should include
	a count of the total number of items available for pagination in UIs.
	count_total is only respected when offset is used. It is ignored when key
	is set.
	*/
	PaginationCountTotal *bool

	/* PaginationKey.

	     key is a value returned in PageResponse.next_key to begin
	querying the next page most efficiently. Only one of offset or key
	should be set.

	     Format: byte
	*/
	PaginationKey *strfmt.Base64

	/* PaginationLimit.

	     limit is the total number of results to be returned in the result page.
	If left empty it will default to a value to be set by each app.

	     Format: uint64
	*/
	PaginationLimit *string

	/* PaginationOffset.

	     offset is a numeric offset that can be used when key is unavailable.
	It is less efficient than using key. Only one of offset or key should
	be set.

	     Format: uint64
	*/
	PaginationOffset *string

	/* PaginationReverse.

	     reverse is set to true if results are to be returned in the descending order.

	Since: cosmos-sdk 0.43
	*/
	PaginationReverse *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the neutron interchain queries registered queries params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NeutronInterchainQueriesRegisteredQueriesParams) WithDefaults() *NeutronInterchainQueriesRegisteredQueriesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the neutron interchain queries registered queries params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NeutronInterchainQueriesRegisteredQueriesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the neutron interchain queries registered queries params
func (o *NeutronInterchainQueriesRegisteredQueriesParams) WithTimeout(timeout time.Duration) *NeutronInterchainQueriesRegisteredQueriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the neutron interchain queries registered queries params
func (o *NeutronInterchainQueriesRegisteredQueriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the neutron interchain queries registered queries params
func (o *NeutronInterchainQueriesRegisteredQueriesParams) WithContext(ctx context.Context) *NeutronInterchainQueriesRegisteredQueriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the neutron interchain queries registered queries params
func (o *NeutronInterchainQueriesRegisteredQueriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the neutron interchain queries registered queries params
func (o *NeutronInterchainQueriesRegisteredQueriesParams) WithHTTPClient(client *http.Client) *NeutronInterchainQueriesRegisteredQueriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the neutron interchain queries registered queries params
func (o *NeutronInterchainQueriesRegisteredQueriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConnectionID adds the connectionID to the neutron interchain queries registered queries params
func (o *NeutronInterchainQueriesRegisteredQueriesParams) WithConnectionID(connectionID *string) *NeutronInterchainQueriesRegisteredQueriesParams {
	o.SetConnectionID(connectionID)
	return o
}

// SetConnectionID adds the connectionId to the neutron interchain queries registered queries params
func (o *NeutronInterchainQueriesRegisteredQueriesParams) SetConnectionID(connectionID *string) {
	o.ConnectionID = connectionID
}

// WithOwners adds the owners to the neutron interchain queries registered queries params
func (o *NeutronInterchainQueriesRegisteredQueriesParams) WithOwners(owners []string) *NeutronInterchainQueriesRegisteredQueriesParams {
	o.SetOwners(owners)
	return o
}

// SetOwners adds the owners to the neutron interchain queries registered queries params
func (o *NeutronInterchainQueriesRegisteredQueriesParams) SetOwners(owners []string) {
	o.Owners = owners
}

// WithPaginationCountTotal adds the paginationCountTotal to the neutron interchain queries registered queries params
func (o *NeutronInterchainQueriesRegisteredQueriesParams) WithPaginationCountTotal(paginationCountTotal *bool) *NeutronInterchainQueriesRegisteredQueriesParams {
	o.SetPaginationCountTotal(paginationCountTotal)
	return o
}

// SetPaginationCountTotal adds the paginationCountTotal to the neutron interchain queries registered queries params
func (o *NeutronInterchainQueriesRegisteredQueriesParams) SetPaginationCountTotal(paginationCountTotal *bool) {
	o.PaginationCountTotal = paginationCountTotal
}

// WithPaginationKey adds the paginationKey to the neutron interchain queries registered queries params
func (o *NeutronInterchainQueriesRegisteredQueriesParams) WithPaginationKey(paginationKey *strfmt.Base64) *NeutronInterchainQueriesRegisteredQueriesParams {
	o.SetPaginationKey(paginationKey)
	return o
}

// SetPaginationKey adds the paginationKey to the neutron interchain queries registered queries params
func (o *NeutronInterchainQueriesRegisteredQueriesParams) SetPaginationKey(paginationKey *strfmt.Base64) {
	o.PaginationKey = paginationKey
}

// WithPaginationLimit adds the paginationLimit to the neutron interchain queries registered queries params
func (o *NeutronInterchainQueriesRegisteredQueriesParams) WithPaginationLimit(paginationLimit *string) *NeutronInterchainQueriesRegisteredQueriesParams {
	o.SetPaginationLimit(paginationLimit)
	return o
}

// SetPaginationLimit adds the paginationLimit to the neutron interchain queries registered queries params
func (o *NeutronInterchainQueriesRegisteredQueriesParams) SetPaginationLimit(paginationLimit *string) {
	o.PaginationLimit = paginationLimit
}

// WithPaginationOffset adds the paginationOffset to the neutron interchain queries registered queries params
func (o *NeutronInterchainQueriesRegisteredQueriesParams) WithPaginationOffset(paginationOffset *string) *NeutronInterchainQueriesRegisteredQueriesParams {
	o.SetPaginationOffset(paginationOffset)
	return o
}

// SetPaginationOffset adds the paginationOffset to the neutron interchain queries registered queries params
func (o *NeutronInterchainQueriesRegisteredQueriesParams) SetPaginationOffset(paginationOffset *string) {
	o.PaginationOffset = paginationOffset
}

// WithPaginationReverse adds the paginationReverse to the neutron interchain queries registered queries params
func (o *NeutronInterchainQueriesRegisteredQueriesParams) WithPaginationReverse(paginationReverse *bool) *NeutronInterchainQueriesRegisteredQueriesParams {
	o.SetPaginationReverse(paginationReverse)
	return o
}

// SetPaginationReverse adds the paginationReverse to the neutron interchain queries registered queries params
func (o *NeutronInterchainQueriesRegisteredQueriesParams) SetPaginationReverse(paginationReverse *bool) {
	o.PaginationReverse = paginationReverse
}

// WriteToRequest writes these params to a swagger request
func (o *NeutronInterchainQueriesRegisteredQueriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ConnectionID != nil {

		// query param connection_id
		var qrConnectionID string

		if o.ConnectionID != nil {
			qrConnectionID = *o.ConnectionID
		}
		qConnectionID := qrConnectionID
		if qConnectionID != "" {

			if err := r.SetQueryParam("connection_id", qConnectionID); err != nil {
				return err
			}
		}
	}

	if o.Owners != nil {

		// binding items for owners
		joinedOwners := o.bindParamOwners(reg)

		// query array param owners
		if err := r.SetQueryParam("owners", joinedOwners...); err != nil {
			return err
		}
	}

	if o.PaginationCountTotal != nil {

		// query param pagination.count_total
		var qrPaginationCountTotal bool

		if o.PaginationCountTotal != nil {
			qrPaginationCountTotal = *o.PaginationCountTotal
		}
		qPaginationCountTotal := swag.FormatBool(qrPaginationCountTotal)
		if qPaginationCountTotal != "" {

			if err := r.SetQueryParam("pagination.count_total", qPaginationCountTotal); err != nil {
				return err
			}
		}
	}

	if o.PaginationKey != nil {

		// query param pagination.key
		var qrPaginationKey strfmt.Base64

		if o.PaginationKey != nil {
			qrPaginationKey = *o.PaginationKey
		}
		qPaginationKey := qrPaginationKey.String()
		if qPaginationKey != "" {

			if err := r.SetQueryParam("pagination.key", qPaginationKey); err != nil {
				return err
			}
		}
	}

	if o.PaginationLimit != nil {

		// query param pagination.limit
		var qrPaginationLimit string

		if o.PaginationLimit != nil {
			qrPaginationLimit = *o.PaginationLimit
		}
		qPaginationLimit := qrPaginationLimit
		if qPaginationLimit != "" {

			if err := r.SetQueryParam("pagination.limit", qPaginationLimit); err != nil {
				return err
			}
		}
	}

	if o.PaginationOffset != nil {

		// query param pagination.offset
		var qrPaginationOffset string

		if o.PaginationOffset != nil {
			qrPaginationOffset = *o.PaginationOffset
		}
		qPaginationOffset := qrPaginationOffset
		if qPaginationOffset != "" {

			if err := r.SetQueryParam("pagination.offset", qPaginationOffset); err != nil {
				return err
			}
		}
	}

	if o.PaginationReverse != nil {

		// query param pagination.reverse
		var qrPaginationReverse bool

		if o.PaginationReverse != nil {
			qrPaginationReverse = *o.PaginationReverse
		}
		qPaginationReverse := swag.FormatBool(qrPaginationReverse)
		if qPaginationReverse != "" {

			if err := r.SetQueryParam("pagination.reverse", qPaginationReverse); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamNeutronInterchainQueriesRegisteredQueries binds the parameter owners
func (o *NeutronInterchainQueriesRegisteredQueriesParams) bindParamOwners(formats strfmt.Registry) []string {
	ownersIR := o.Owners

	var ownersIC []string
	for _, ownersIIR := range ownersIR { // explode []string

		ownersIIV := ownersIIR // string as string
		ownersIC = append(ownersIC, ownersIIV)
	}

	// items.CollectionFormat: "multi"
	ownersIS := swag.JoinByFormat(ownersIC, "multi")

	return ownersIS
}
