// Code generated by go-swagger; DO NOT EDIT.

package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new query API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for query API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	IbcCoreConnectionV1Connection(params *IbcCoreConnectionV1ConnectionParams, opts ...ClientOption) (*IbcCoreConnectionV1ConnectionOK, error)

	NeutronInterchainQueriesRegisteredQueries(params *NeutronInterchainQueriesRegisteredQueriesParams, opts ...ClientOption) (*NeutronInterchainQueriesRegisteredQueriesOK, error)

	NeutronInterchainQueriesRegisteredQuery(params *NeutronInterchainQueriesRegisteredQueryParams, opts ...ClientOption) (*NeutronInterchainQueriesRegisteredQueryOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
IbcCoreConnectionV1Connection connections queries an i b c connection end
*/
func (a *Client) IbcCoreConnectionV1Connection(params *IbcCoreConnectionV1ConnectionParams, opts ...ClientOption) (*IbcCoreConnectionV1ConnectionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIbcCoreConnectionV1ConnectionParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "IbcCoreConnectionV1Connection",
		Method:             "GET",
		PathPattern:        "/ibc/core/connection/v1/connections/{connection_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &IbcCoreConnectionV1ConnectionReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*IbcCoreConnectionV1ConnectionOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*IbcCoreConnectionV1ConnectionDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
NeutronInterchainQueriesRegisteredQueries neutron interchain queries registered queries API
*/
func (a *Client) NeutronInterchainQueriesRegisteredQueries(params *NeutronInterchainQueriesRegisteredQueriesParams, opts ...ClientOption) (*NeutronInterchainQueriesRegisteredQueriesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewNeutronInterchainQueriesRegisteredQueriesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "NeutronInterchainQueriesRegisteredQueries",
		Method:             "GET",
		PathPattern:        "/neutron/interchainqueries/registered_queries",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &NeutronInterchainQueriesRegisteredQueriesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*NeutronInterchainQueriesRegisteredQueriesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*NeutronInterchainQueriesRegisteredQueriesDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
NeutronInterchainQueriesRegisteredQuery neutron interchain queries registered query API
*/
func (a *Client) NeutronInterchainQueriesRegisteredQuery(params *NeutronInterchainQueriesRegisteredQueryParams, opts ...ClientOption) (*NeutronInterchainQueriesRegisteredQueryOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewNeutronInterchainQueriesRegisteredQueryParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "NeutronInterchainQueriesRegisteredQuery",
		Method:             "GET",
		PathPattern:        "/neutron/interchainqueries/registered_query",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &NeutronInterchainQueriesRegisteredQueryReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*NeutronInterchainQueriesRegisteredQueryOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*NeutronInterchainQueriesRegisteredQueryDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
