// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// NeutronInterchainadapterInterchainqueriesMsgUpdateInterchainQueryResponse neutron interchainadapter interchainqueries msg update interchain query response
//
// swagger:model neutron.interchainadapter.interchainqueries.MsgUpdateInterchainQueryResponse
type NeutronInterchainadapterInterchainqueriesMsgUpdateInterchainQueryResponse interface{}
