// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NeutronInterchainadapterInterchaintxsQueryInterchainAccountAddressResponse Query response for an interchain account address
//
// swagger:model neutron.interchainadapter.interchaintxs.QueryInterchainAccountAddressResponse
type NeutronInterchainadapterInterchaintxsQueryInterchainAccountAddressResponse struct {

	// The corresponding interchain account address on the host chain
	InterchainAccountAddress string `json:"interchain_account_address,omitempty"`
}

// Validate validates this neutron interchainadapter interchaintxs query interchain account address response
func (m *NeutronInterchainadapterInterchaintxsQueryInterchainAccountAddressResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this neutron interchainadapter interchaintxs query interchain account address response based on context it is used
func (m *NeutronInterchainadapterInterchaintxsQueryInterchainAccountAddressResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NeutronInterchainadapterInterchaintxsQueryInterchainAccountAddressResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NeutronInterchainadapterInterchaintxsQueryInterchainAccountAddressResponse) UnmarshalBinary(b []byte) error {
	var res NeutronInterchainadapterInterchaintxsQueryInterchainAccountAddressResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
