// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NeutronInterchainqueriesRegisteredQuery neutron interchainqueries registered query
//
// swagger:model neutron.interchainqueries.RegisteredQuery
type NeutronInterchainqueriesRegisteredQuery struct {

	// The IBC connection ID for getting ConsensusState to verify proofs
	ConnectionID string `json:"connection_id,omitempty"`

	// The unique id of the registered query.
	ID string `json:"id,omitempty"`

	// The KV-storage keys for which we want to get values from remote chain
	Keys []*NeutronInterchainqueriesRegisteredQueryKeysItems0 `json:"keys"`

	// The local chain last block height when the query result was updated.
	LastSubmittedResultLocalHeight string `json:"last_submitted_result_local_height,omitempty"`

	// last submitted result remote height
	LastSubmittedResultRemoteHeight *NeutronInterchainqueriesRegisteredQueryLastSubmittedResultRemoteHeight `json:"last_submitted_result_remote_height,omitempty"`

	// The address that registered the query.
	Owner string `json:"owner,omitempty"`

	// The query type identifier: `kv` or `tx` now
	QueryType string `json:"query_type,omitempty"`

	// The filter for transaction search ICQ
	TransactionsFilter string `json:"transactions_filter,omitempty"`

	// Parameter that defines how often the query must be updated.
	UpdatePeriod string `json:"update_period,omitempty"`
}

// Validate validates this neutron interchainqueries registered query
func (m *NeutronInterchainqueriesRegisteredQuery) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKeys(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastSubmittedResultRemoteHeight(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NeutronInterchainqueriesRegisteredQuery) validateKeys(formats strfmt.Registry) error {
	if swag.IsZero(m.Keys) { // not required
		return nil
	}

	for i := 0; i < len(m.Keys); i++ {
		if swag.IsZero(m.Keys[i]) { // not required
			continue
		}

		if m.Keys[i] != nil {
			if err := m.Keys[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("keys" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("keys" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *NeutronInterchainqueriesRegisteredQuery) validateLastSubmittedResultRemoteHeight(formats strfmt.Registry) error {
	if swag.IsZero(m.LastSubmittedResultRemoteHeight) { // not required
		return nil
	}

	if m.LastSubmittedResultRemoteHeight != nil {
		if err := m.LastSubmittedResultRemoteHeight.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("last_submitted_result_remote_height")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("last_submitted_result_remote_height")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this neutron interchainqueries registered query based on the context it is used
func (m *NeutronInterchainqueriesRegisteredQuery) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateKeys(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLastSubmittedResultRemoteHeight(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NeutronInterchainqueriesRegisteredQuery) contextValidateKeys(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Keys); i++ {

		if m.Keys[i] != nil {
			if err := m.Keys[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("keys" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("keys" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *NeutronInterchainqueriesRegisteredQuery) contextValidateLastSubmittedResultRemoteHeight(ctx context.Context, formats strfmt.Registry) error {

	if m.LastSubmittedResultRemoteHeight != nil {
		if err := m.LastSubmittedResultRemoteHeight.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("last_submitted_result_remote_height")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("last_submitted_result_remote_height")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *NeutronInterchainqueriesRegisteredQuery) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NeutronInterchainqueriesRegisteredQuery) UnmarshalBinary(b []byte) error {
	var res NeutronInterchainqueriesRegisteredQuery
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// NeutronInterchainqueriesRegisteredQueryKeysItems0 neutron interchainqueries registered query keys items0
//
// swagger:model NeutronInterchainqueriesRegisteredQueryKeysItems0
type NeutronInterchainqueriesRegisteredQueryKeysItems0 struct {

	// Key you want to read from the storage
	// Format: byte
	Key strfmt.Base64 `json:"key,omitempty"`

	// Path (storage prefix) to the storage where you want to read value by key (usually name of cosmos-sdk module: 'staking', 'bank', etc.)
	Path string `json:"path,omitempty"`
}

// Validate validates this neutron interchainqueries registered query keys items0
func (m *NeutronInterchainqueriesRegisteredQueryKeysItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this neutron interchainqueries registered query keys items0 based on context it is used
func (m *NeutronInterchainqueriesRegisteredQueryKeysItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NeutronInterchainqueriesRegisteredQueryKeysItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NeutronInterchainqueriesRegisteredQueryKeysItems0) UnmarshalBinary(b []byte) error {
	var res NeutronInterchainqueriesRegisteredQueryKeysItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// NeutronInterchainqueriesRegisteredQueryLastSubmittedResultRemoteHeight The remote chain last block height & revision number when the query result was updated.
//
// swagger:model NeutronInterchainqueriesRegisteredQueryLastSubmittedResultRemoteHeight
type NeutronInterchainqueriesRegisteredQueryLastSubmittedResultRemoteHeight struct {

	// revision height
	RevisionHeight string `json:"revision_height,omitempty"`

	// revision number
	RevisionNumber string `json:"revision_number,omitempty"`
}

// Validate validates this neutron interchainqueries registered query last submitted result remote height
func (m *NeutronInterchainqueriesRegisteredQueryLastSubmittedResultRemoteHeight) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this neutron interchainqueries registered query last submitted result remote height based on context it is used
func (m *NeutronInterchainqueriesRegisteredQueryLastSubmittedResultRemoteHeight) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NeutronInterchainqueriesRegisteredQueryLastSubmittedResultRemoteHeight) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NeutronInterchainqueriesRegisteredQueryLastSubmittedResultRemoteHeight) UnmarshalBinary(b []byte) error {
	var res NeutronInterchainqueriesRegisteredQueryLastSubmittedResultRemoteHeight
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
