// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// NeutronInterchainadapterInterchaintxsV1MsgSubmitTxResponse MsgSubmitTxResponse defines the response for Msg/SubmitTx
//
// swagger:model neutron.interchainadapter.interchaintxs.v1.MsgSubmitTxResponse
type NeutronInterchainadapterInterchaintxsV1MsgSubmitTxResponse interface{}
