// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// NeutronInterchainadapterInterchainqueriesMsgRemoveInterchainQueryResponse neutron interchainadapter interchainqueries msg remove interchain query response
//
// swagger:model neutron.interchainadapter.interchainqueries.MsgRemoveInterchainQueryResponse
type NeutronInterchainadapterInterchainqueriesMsgRemoveInterchainQueryResponse interface{}
